### ISSUE TITLE
Access token invalid or no longer valid

### ISSUE THREAD

**Issue by mrmyn** [oott123/alfred-clipboard-ocr#13]
Alfred版本:4.3.4(1229)
错误日志:
[09:22:18.374] ERROR: OCR Clipboard[Run Script] request failed, clear credentials cache and try again
Access token invalid or no longer valid
undefined method `stack' for #<RuntimeError: Access token invalid or no longer valid>
/Users/users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AF61A4F3-DC7F-4185-A1A1-C0B069FC73CF/ocr.rb:119:in `rescue in <main>': undefined method `stack' for #<NoMethodError:0x00007fb4aa0ccf68> (NoMethodError)
	from /Users/users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AF61A4F3-DC7F-4185-A1A1-C0B069FC73CF/ocr.rb:90:in `<main>'
/Users/users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AF61A4F3-DC7F-4185-A1A1-C0B069FC73CF/ocr.rb:101:in `rescue in <main>': undefined method `stack' for #<RuntimeError: Access token invalid or no longer valid> (NoMethodError)
	from /Users/users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AF61A4F3-DC7F-4185-A1A1-C0B069FC73CF/ocr.rb:96:in `<main>'
/Users/users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AF61A4F3-DC7F-4185-A1A1-C0B069FC73CF/ocr.rb:71:in `ocr_text': Access token invalid or no longer valid (RuntimeError)
	from /Users/users/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AF61A4F3-DC7F-4185-A1A1-C0B069FC73CF/ocr.rb:97:in `<main>'
[09:22:18.383] OCR Clipboard[Run Script] Processing complete
[09:22:18.384] OCR Clipboard[Run Script] Passing output 'something' to Post Notification

**Comment by mrmyn** [comment]
使用的已经实名认证后赠送的ocr

**Comment by oott123** [comment]
需要手动删除一下本地的 access token 才行。

数据文件位置如下：

```
~/Library/Application Support/Alfred/Workflow Data/com.oott123.alfred.clipboard.ocr/.alfred_ocr_credentials
```

删除该文件后应当可以正常工作。

**Comment by funabashi-cn** [comment]
谢谢大神！！！ 搞定了
