### ISSUE TITLE
Access token invalid or no longer valid

### ISSUE THREAD

**Issue by fanlb** [oott123/alfred-clipboard-ocr#14]
* ![ocr_failure](https://user-images.githubusercontent.com/6261608/126732424-bc17574d-1576-4389-81c6-1cc5e5df0a76.jpg)
* ![Snipaste_2021-07-23_10-51-25](https://user-images.githubusercontent.com/6261608/126732509-be4691b6-8b74-4125-9287-deba713b3dec.jpg)

* Appkey: MgQbGMdyQZ4d4MQGQc3qXvQl
* AppSecret: p2DoLX2wvBZGy4M4dwGq6odbS4ZO2gw9
* Hi, 你好 我这边一直在报 `Access token invalid or no longer valid`  试过 关闭SSR/重新创建appkey/免费资源还是不行,  麻烦帮忙看下, 谢谢

**Comment by funabashi-cn** [comment]
同样的问题，一直出错。。。。
实名后了，也领了免费的额度了。还是一直报这个错误。。。希望作者来帮诊断一下啊。

**Comment by oott123** [comment]
dup with #13

**Comment by oott123** [comment]
不要把你的 secret 发到公开的 issue 列表里。建议你现在重新生成你的 secret，避免被其他人使用。
