### ISSUE TITLE
Access token invalid or no longer valid

### ISSUE THREAD

**Issue by funabashi-cn** [oott123/alfred-clipboard-ocr#15]
[13:01:10.535] OCR Clipboard[Keyword] Processing complete
[13:01:10.538] OCR Clipboard[Keyword] Passing output '' to Run Script
[13:01:10.886] ERROR: OCR Clipboard[Run Script] request failed, clear credentials cache and try again
Access token invalid or no longer valid
undefined method `stack' for #<RuntimeError: Access token invalid or no longer valid>
/Users/yun/Documents/Alfred.alfredpreferences/workflows/user.workflow.E318D9FD-0B38-44B9-A04B-31A255C7F84C/ocr.rb:119:in `rescue in <main>': undefined method `stack' for #<NoMethodError:0x00007f83db115fb0> (NoMethodError)
	from /Users/yun/Documents/Alfred.alfredpreferences/workflows/user.workflow.E318D9FD-0B38-44B9-A04B-31A255C7F84C/ocr.rb:90:in `<main>'
/Users/yun/Documents/Alfred.alfredpreferences/workflows/user.workflow.E318D9FD-0B38-44B9-A04B-31A255C7F84C/ocr.rb:101:in `rescue in <main>': undefined method `stack' for #<RuntimeError: Access token invalid or no longer valid> (NoMethodError)
	from /Users/yun/Documents/Alfred.alfredpreferences/workflows/user.workflow.E318D9FD-0B38-44B9-A04B-31A255C7F84C/ocr.rb:96:in `<main>'
/Users/yun/Documents/Alfred.alfredpreferences/workflows/user.workflow.E318D9FD-0B38-44B9-A04B-31A255C7F84C/ocr.rb:71:in `ocr_text': Access token invalid or no longer valid (RuntimeError)
	from /Users/yun/Documents/Alfred.alfredpreferences/workflows/user.workflow.E318D9FD-0B38-44B9-A04B-31A255C7F84C/ocr.rb:97:in `<main>'
[13:01:10.890] OCR Clipboard[Run Script] Processing complete
[13:01:10.901] OCR Clipboard[Run Script] Passing output 'something' to Post Notification

**Comment by funabashi-cn** [comment]
请大神来帮诊断一下病情啊。。。。  
百度那边实名认证了，免费额度也都领了啊。

**Comment by oott123** [comment]
dup with #14
