### ISSUE TITLE
提示 pngpaste 无法打开，说未经验证。请帮看一下啊。OS X 12.1

### ISSUE THREAD

**Issue by osaka2020** [oott123/alfred-clipboard-ocr#19]
![iShot2022-01-14 11 47 33](https://user-images.githubusercontent.com/93255760/149448287-d2303058-8cdc-4a7b-b4eb-91afd3827330.jpg)

**Comment by oott123** [comment]
这是个 macOS 专有系统的使用问题，应该可以到 google 等搜索引擎上寻求到答案。

由于我个人不再日常使用 macOS，所以这个 issue 留给其他人回答。

**Comment by osaka2020** [comment]
谢谢！Google了一下，找到了pngpaste的所在位置，打开了。。。谢谢提醒！
