### ISSUE TITLE
Bad URI

### ISSUE THREAD

**Issue by Baogaitou** [oott123/alfred-clipboard-ocr#2]
提示：Bad URI（is Not url?）127.0.0.1:6152
已经配置了 Key 和 Secret.

**Comment by oott123** [comment]
![default](https://user-images.githubusercontent.com/905663/33647813-dda2b36c-da91-11e7-99d8-96f0f7a2dab9.png)

请打开 Alfred 设置，找到这个工作流，然后点右上角的 debug 图标，并在底栏切换到 All Infomation。
此后，截图并尝试执行  OCR，将日志的信息粘贴到 issue 中。
感谢你的耐心。

另外请看看 6152 是否是您本地的代理端口；以及，在编辑环境变量里，把 http_proxy HTTP_PROXY https_proxy HTTPS_PROXY 这几个都加进去，值留空能否解决这个问题。谢谢！

**Comment by Baogaitou** [comment]
已经确认是本地代理的问题，之前没有注意到，非常感谢回复，双手点赞 ;p

**Comment by oott123** [comment]
已经增加了[相关说明](https://github.com/oott123/alfred-clipboard-ocr#%E5%BC%80%E4%BA%86%E4%BB%A3%E7%90%86%E5%B0%B1%E6%8A%A5%E9%94%99)。
