### ISSUE TITLE
ERROR: OCR Clipboard[Run Script] request failed, clear credentials cache and try again

### ISSUE THREAD

**Issue by zouchao** [oott123/alfred-clipboard-ocr#21]
Open api qps request limit reached
undefined method `stack' for #<RuntimeError: Open api qps request limit reached>
/Users/zouchao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3321488B-C90C-431F-A0E9-5B7790A43423/ocr.rb:119:in `rescue in <main>': undefined method `stack' for #<NoMethodError:0x00000001509cf1e8> (NoMethodError)
	from /Users/zouchao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3321488B-C90C-431F-A0E9-5B7790A43423/ocr.rb:90:in `<main>'
/Users/zouchao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3321488B-C90C-431F-A0E9-5B7790A43423/ocr.rb:101:in `rescue in <main>': undefined method `stack' for #<RuntimeError: Open api qps request limit reached> (NoMethodError)
	from /Users/zouchao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3321488B-C90C-431F-A0E9-5B7790A43423/ocr.rb:96:in `<main>'
/Users/zouchao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3321488B-C90C-431F-A0E9-5B7790A43423/ocr.rb:71:in `ocr_text': Open api qps request limit reached (RuntimeError)
	from /Users/zouchao/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.3321488B-C90C-431F-A0E9-5B7790A43423/ocr.rb:97:in `<main>'

**Comment by zouchao** [comment]
Alfred version 4.6.6

**Comment by oott123** [comment]
#12
