### ISSUE TITLE
关于开代理报错修复

### ISSUE THREAD

**Issue by Vxider** [oott123/alfred-clipboard-ocr#3]
Alfred全局代理设置中可以修复代理报错问题：
<img width="303" alt="2018-03-23 09 56 38" src="https://user-images.githubusercontent.com/6134315/37807484-a5fafd82-2e80-11e8-9718-f3f7abd3bdc6.png">

**Comment by oott123** [comment]
你好，看起来这个设置是对所有 Alfred workflow 都生效的。[README](https://github.com/oott123/alfred-clipboard-ocr#%E5%BC%80%E4%BA%86%E4%BB%A3%E7%90%86%E5%B0%B1%E6%8A%A5%E9%94%99) 里说明的这种方法，是只对当前 workflow 生效的。

**Comment by Vxider** [comment]
你好，是这样的，因为看到有人在问这个问题，为了避免其他插件出现类似问题无法解决，我把这个方法贴出来给遇到问题的朋友一个选择。
