### ISSUE TITLE
百度api配置完成了，输入ocr无效

### ISSUE THREAD

**Issue by jfhufhf** [oott123/alfred-clipboard-ocr#4]
以下为打开debug模式之后的提示信息：
[2018-05-30 15:18:20][input.keyword] Processing output of 'action.script' with arg ''
[2018-05-30 15:18:20][ERROR: action.script] pngpaste: No image data found on the clipboard, or could not convert!
No image found in your clipboard.
/Users/***/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.22F22156-520F-4262-A183-4D3FB45F9B42/ocr.rb:119:in `rescue in <main>': undefined method `stack' for #<RuntimeError: No image found in your clipboard.> (NoMethodError)
	from /Users/****/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.22F22156-520F-4262-A183-4D3FB45F9B42/ocr.rb:90:in `<main>'
[2018-05-30 15:18:20][action.script] Processing output of 'output.notification' with arg 'something'

**Comment by oott123** [comment]
你好，看报错信息，你需要先复制一个图片到剪贴板中。

注意我们无法识别复制的图片文件，而只能识别图片——比如，截图软件（类似 Snipaste 、QQ 截图或者系统截图）复制到剪贴板中的那种。

**Comment by jfhufhf** [comment]
感谢您的回复，我这边使用的是微信和QQ的截图软件，截图成功进入剪贴板之后，输入ocr还是出现已上错误。

**Comment by jfhufhf** [comment]
已经成功解决这个问题了,是第一次粘贴图片进去不行,之后就可以了

**Comment by oott123** [comment]
如果是这样，那也许是 pngpaste 的 bug，我可能无力解决。
