### ISSUE TITLE
中文和英文混合以及英文旁附有参考文献时识别出错

### ISSUE THREAD

**Issue by lihongweimail** [oott123/alfred-clipboard-ocr#6]
![image](https://user-images.githubusercontent.com/2408935/49631055-8fecd200-fa2b-11e8-816b-dbcb9c5a34b8.png)
识别后的的结果：
------------
等进行推理。规则推理在大型知识图谱上的效率受限于它的离散性, Cohen提出了一个
可微的规则推理机 Tensorlog'11
------------

![image](https://user-images.githubusercontent.com/2408935/49631114-b7439f00-fa2b-11e8-96fe-2158ca762a21.png)
识别后的的结果：

------------
的三维张量,通过张量分解得到实体和关系的表示。考虑到知识图谱中的多步推理的表
示学习方法有 PTransE10、CVSM10等。
------

**Comment by oott123** [comment]
插件调用的是百度的 OCR 接口，返回结果不准确请向百度方面反馈……插件不做任何处理，谢谢您的理解。
